local option = vim.opt
local buffer = vim.b
local global = vim.g

option.showmode = true
option.expandtab = true
option.showmode = false
option.tabstop = 4
option.shiftwidth = 4
option.shiftround = true
option.autoindent = true
option.smartindent = true
option.number = true
option.rnu = true
option.wildmenu = true
option.hlsearch = false
option.ic = false
option.smartcase = false
option.cul = true
option.autoread = true
option.completeopt = {"menu","menuone"}
option.termguicolors = true
option.signcolumn = "yes"
option.title = true
option.swapfile = false
option.backup = false
option.updatetime = 50
option.mouse = "a"
option.undofile = true
option.undodir = vim.fn.expand('$HOME/.local/share/nvim/undo')
option.exrc=true
